os:
  - linux
  # - osx
env:
  - NOWAL=1 OPENBLAS_NUM_THREADS=1
language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install Cython --install-option="--no-cython-compile"
  - pip install coverage pytest pytest-cov -U
  - pip install lxml pyteomics
  - pip install --only-binary=numpy,scipy numpy scipy==0.19.0
  - pip install -r external-requirements.txt
  - python pyinstaller/install-from-git.py
  - pip install PyInstaller dis3
  - python setup.py install
script: make test build-pyinstaller